### ISSUE TITLE
fresh installation throws hostOrText.readFile is not a function

### ISSUE THREAD

**Issue by prowseed** [mtmeyer/create-react-figma-plugin#8]
Going along with readme, after running npm run dev it's not building index.ts

**Comment by prowseed** [comment]
I can confirm this happens only for typescript version 4.9, but it's ok downgraded to typescript 4.8.3
most likely `@rollup/plugin-node-resolve` not prepared for ts 4.9

**Comment by mtmeyer** [comment]
@prowseed Thanks for pointing this out 🙏, I'll look into it over the next few days and find a solution so that it works out of the box.

**Comment by mtmeyer** [comment]
Has been fixed in https://github.com/mtmeyer/create-react-figma-plugin/commit/0f06ceb242ca9d398d673966808c277e8c73a093

Thanks again @prowseed for the heads up.

**Comment by mtmeyer** [comment]
Has been fixed in https://github.com/mtmeyer/create-react-figma-plugin/commit/0f06ceb242ca9d398d673966808c277e8c73a093

Thanks again @prowseed for the heads up.
